name: Build, Scan, and Publish Docker Image to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Multi-Arch Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:latest

  trivy_scan:
    name: Scan Docker Image for Vulnerabilities
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

    - name: Scan Docker Image
      run: |
        ./trivy image --severity HIGH,CRITICAL --exit-code 1 ghcr.io/${{ github.repository }}:latest

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build, trivy_scan]

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish SBOM (optional)
      run: |
        echo "SBOM generation logic here if required"

    - name: Publish Provenance (optional)
      run: |
        echo "Provenance file generation logic here if required"

    - name: Docker Build and Push (if Trivy scan passed)
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
